name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: [ubuntu-24.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      - name: Clippy Check
        run: cargo clippy -- --deny warnings
      - name: Run tests
        run: cargo test
